name: skipapp-hello
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  verify-app:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - uses: actions/checkout@v4
        with:
          path: skipapp-hello-repo
      - name: Compare hello-skip template with skipapp-hello repo
        run: |
          brew install skiptools/skip/skip
          ./skipapp-hello-repo/scripts/diff_template.sh skipapp-hello skipapp-hello-repo
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-app.yml@main

