name: skipapp-hello
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  verify-app:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - run: brew install skiptools/skip/skip
      - uses: actions/checkout@v3
        with:
          path: skipapp-hello-repo
      - name: Compare hello-skip template with skipapp-hello repo
        run: |
          brew install skiptools/skip/skip
          skip init --appid=skip.hello.App --version 1.0.0 skipapp-hello HelloSkip
          # make sure that the repo exactly matches the template,
          # allowing for changes in some files, as well as
          # dependency versions
          diff --exclude=README.md --exclude=.build --exclude=.git --exclude=.github --exclude=.gitignore --exclude=Package.resolved --exclude=Skip.env --exclude=Localizable.xcstrings --exclude=project.xcworkspace --exclude=proguard-rules.pro -I 'url: "https://source.skip.tools/' -r skipapp-hello/ skipapp-hello-repo/

  call-workflow:
    uses: skiptools/skip/.github/workflows/skip-app.yml@main

